# Generated by Django 3.0.6 on 2020-05-14 11:39

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', netfields.fields.InetAddressField(max_length=39)),
                ('description', models.CharField(max_length=200, null=True)),
                ('vlan', models.IntegerField(null=True)),
            ],
        ),
    ]
