# Generated by Django 3.0.6 on 2020-12-02 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')])),
                ('network_binary', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Дескрипшн')),
                ('trash_image', models.CharField(default='/static/Photo/Trash2.png', max_length=100)),
            ],
            options={
                'verbose_name': 'Class network',
                'ordering': ('network_binary',),
            },
        ),
        migrations.CreateModel(
            name='PAT',
            fields=[
                ('geokod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('geokod',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя региона')),
                ('region_type', models.CharField(choices=[('core', 'Ядро'), ('pat', 'ПАТ')], max_length=10)),
                ('geokod', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Region',
                'ordering': ('geokod',),
            },
        ),
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')])),
                ('network_binary', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('network_binary',),
            },
        ),
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pool', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')])),
                ('network_binary', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('classNetwork_reletionship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_net.ClassNetwork', verbose_name='Классовая сеть')),
            ],
            options={
                'verbose_name': 'VPN pool',
                'ordering': ('network_binary',),
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField(verbose_name='VLAN')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('trash_image', models.CharField(default='/static/Photo/Trash2.png', max_length=100)),
                ('region_reletionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_net.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'VLAN',
                'ordering': ('vlan_id',),
                'unique_together': {('vlan_id', 'region_reletionship')},
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')])),
                ('network_binary', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('classNetwork_reletionship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_net.ClassNetwork', verbose_name='Классовая сеть')),
                ('region_reletionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_net.Region', verbose_name='Регион')),
                ('vlan_reletionship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_net.VLAN', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'Network',
                'ordering': ('network_binary',),
                'unique_together': {('network',)},
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('network_reletionship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.Networks')),
                ('testDB_reletionship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.TestDB')),
                ('vpnPool_reletionship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.VPN')),
            ],
            options={
                'ordering': ('ip_address',),
            },
        ),
    ]
