# Generated by Django 3.0.6 on 2020-05-23 17:50

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя региона')),
            ],
            options={
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField(verbose_name='VLAN')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('region_reletionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_net.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'VLAN',
                'ordering': ('vlan_id',),
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', netfields.fields.InetAddressField(max_length=39, verbose_name='Сеть')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('region_reletionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_net.Region', verbose_name='Регион')),
                ('vlan_reletionship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_net.VLAN', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'Network',
                'ordering': ('network',),
            },
        ),
    ]
