# Generated by Django 3.0.6 on 2020-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnetwork',
            name='trash_image',
            field=models.CharField(default='/static/Photo/Trash2.png', max_length=100),
        ),
    ]
