# Generated by Django 3.0.6 on 2020-05-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('network_reletionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_net.Networks')),
            ],
        ),
    ]
