# Generated by Django 3.0.6 on 2020-12-03 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='adress',
            name='network_binary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networks',
            name='network',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')], verbose_name='Сеть'),
        ),
    ]
