# Generated by Django 3.0.6 on 2020-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('network',),
            },
        ),
    ]
