# Generated by Django 3.0.6 on 2020-12-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0002_auto_20201203_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ('ip_address',)},
        ),
    ]
