# Generated by Django 3.0.6 on 2020-11-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0002_classnetwork_trash_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classnetwork',
            old_name='ip',
            new_name='id',
        ),
    ]
