# Generated by Django 3.0.6 on 2020-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0002_testdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='network_binary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
