# Generated by Django 3.0.6 on 2020-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0003_testdb_network_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdb',
            name='network_binary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
