# Generated by Django 3.0.6 on 2020-07-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0003_adress_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='arrow_image',
            field=models.CharField(default='/static/Photo/Arrow.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='adress',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='networks',
            name='vlan_reletionship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_net.VLAN', verbose_name='VLAN'),
        ),
    ]
