# Generated by Django 3.0.6 on 2020-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0004_auto_20200704_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstTunnelName', models.CharField(max_length=30)),
                ('firstTunnelPhisicalAddress', models.GenericIPAddressField()),
                ('firstTunnelNetworkAddress', models.GenericIPAddressField()),
                ('secondTunnelName', models.CharField(max_length=30)),
                ('secondTunnelPhisicalAddress', models.GenericIPAddressField()),
                ('secondTunnelNetworkAddress', models.GenericIPAddressField()),
            ],
            options={
                'ordering': ('firstTunnelPhisicalAddress', 'secondTunnelPhisicalAddress'),
            },
        ),
    ]
