# Generated by Django 3.0.6 on 2020-08-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0005_tunnels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ('ip_address',)},
        ),
    ]
