# Generated by Django 3.0.6 on 2020-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0005_auto_20201201_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdb',
            name='network_binary',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
