# Generated by Django 3.0.6 on 2020-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0006_auto_20201201_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdb',
            name='network_binary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
