# Generated by Django 3.0.6 on 2020-08-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0007_auto_20200801_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BO',
            new_name='PAT',
        ),
    ]
