# Generated by Django 3.0.6 on 2020-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0009_auto_20200802_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='core',
        ),
        migrations.RemoveField(
            model_name='region',
            name='other',
        ),
        migrations.RemoveField(
            model_name='region',
            name='pat',
        ),
        migrations.AddField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('Ядро', 'core'), ('ПАТ', 'pat'), ('Другое', 'other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
