# Generated by Django 3.0.6 on 2020-12-02 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0010_auto_20201202_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='arrow_image',
        ),
        migrations.AddField(
            model_name='adress',
            name='testDB_reletionship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.TestDB'),
        ),
        migrations.AlterField(
            model_name='testdb',
            name='network',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid network', message='Неверный формат сети', regex='^(([1-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.)(([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){2}([0-9]|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\/([1-9]|[1-2]\\d|3[0-2])$')]),
        ),
    ]
