# Generated by Django 3.0.6 on 2020-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0010_auto_20200802_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('core', 'Ядро'), ('pat', 'ПАТ'), ('other', 'Другое')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('vlan_id', 'region_reletionship')},
        ),
    ]
