# Generated by Django 3.0.6 on 2020-08-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0011_auto_20200802_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networks',
            unique_together={('network', 'region_reletionship')},
        ),
    ]
