# Generated by Django 3.0.6 on 2020-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0012_auto_20200811_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='geokod',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
