# Generated by Django 3.0.6 on 2020-09-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0014_auto_20200819_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networks',
            unique_together={('network', 'vlan_reletionship'), ('network', 'region_reletionship')},
        ),
    ]
