# Generated by Django 3.0.6 on 2020-09-10 15:24

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0015_auto_20200910_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='network',
            field=netfields.fields.InetAddressField(max_length=39, unique=True, verbose_name='Сеть'),
        ),
        migrations.AlterUniqueTogether(
            name='networks',
            unique_together={('network', 'vlan_reletionship')},
        ),
    ]
