# Generated by Django 3.0.6 on 2020-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0016_auto_20200910_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='trash_image',
            field=models.CharField(default='/static/Photo/Trash2.png', max_length=100),
        ),
    ]
