# Generated by Django 3.0.6 on 2020-10-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0018_auto_20201020_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpn',
            options={'ordering': ('pool',), 'verbose_name': 'VPN pool'},
        ),
        migrations.RenameField(
            model_name='vpn',
            old_name='pull',
            new_name='pool',
        ),
    ]
