# Generated by Django 3.0.6 on 2020-10-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0019_auto_20201020_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='vpnPool_reletionship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.VPN'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='network_reletionship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.Networks'),
        ),
    ]
