# Generated by Django 3.0.6 on 2020-10-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0021_auto_20201022_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='network_reletionship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.Networks'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vpnPool_reletionship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.VPN'),
        ),
    ]
