# Generated by Django 3.0.6 on 2020-10-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0022_auto_20201022_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='vpnPool_reletionship',
        ),
    ]
