# Generated by Django 3.0.6 on 2020-10-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_net', '0024_auto_20201022_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='vpnPool_reletionship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_net.VPN'),
        ),
    ]
